services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/uc_quantum
    ports:
      - "8888:8888"
    # command: ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--allow-root"]
    command: ["tail", "-f", "/dev/null"]
